GET http://localhost:5000/api/v1/accounts

###

GET http://localhost:5000/data/dashboard
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubmllIiwicGFzc3dvcmQiOjEyMywiaWF0IjoxNjg5MDU3NDIwLCJleHAiOjE2ODkwNTc0NTB9.2f3X0PgOWzzKr8tOMisVyq2GBaD5C1jK3RI2ytCDyXg

###
POST http://localhost:5000/login
Content-type: application/json

{
    "username": "annie",
    "password": 123
}